[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project]
name = "solarpandas"
version = "0.1.0"
description = "Analysis of solar irradiance time series with pandas"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Jose A Ruiz Arias", email = "jararias@uma.es" }]
license = {text = "CC-BY-NC-SA-4.0"}
keywords = ["solar", "irradiance", "timeseries", "pandas", "bsrn", "photovoltaics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "License :: Free To Use But Restricted",
]

dependencies = [
    "colorcet>=3.2.1",
    "datashader>=0.19.1",
    "loguru>=0.7.3",
    "lxml>=6.1.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "platformdirs>=4.9.6",
    "pyarrow>=24.0.0",
    "sparta-solar>=0.1.0",
    "sunwhere>=1.4.1",
    "tomlkit>=0.15.0",
]

[project.urls]
Homepage = "https://github.com/jararias/solarpandas"
Documentation = "https://jararias.github.io/solarpandas"
Repository = "https://github.com/jararias/solarpandas"
Issues = "https://github.com/jararias/solarpandas/issues"

[dependency-groups]
docs = [
    "mkdocstrings[python]>=1.0.4",
    "pymdown-extensions>=10.21.3",
    "zensical>=0.0.43",
]
dev = [
    {include-group = "docs"},
    "genbadge[all]>=1.1.3",
    "ipython>=9.13.0",
    "pykeepass>=4.1.1.post1",
    "pyqt6>=6.11.0",
    "pytest>=8.0.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "network: mark test as requiring network access",
]

[tool.coverage.run]
omit = [
    "**/*.pyx",
]

[tool.uv.build-backend]
# Incluye archivos o carpetas específicas en el paquete final
source-include = [
    "src/solarpandas/sample_data/*.parquet",
    "src/solarpandas/mplstyles/*.mplstyle",
]
